title: Blast Off Theme
author: swissChili
email: sasha@stomprocket.io
description: > # this means to ignore newlines until "baseurl:"
  This is a minimal and simple Jekyll theme built with Blast Off. It is very simple,
  quite scalable. Perfect for blogs and websites.

# social links
# twitter_username: @swissChili
github_username:  swissChili
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme:
exclude:
  - Gemfile
  - Gemfile.lock
